// Generated by Selenium IDE
require('chromedriver');
const { Builder, By, Key, until } = require('selenium-webdriver');


(async function test() {

      try {
  this.timeout(30000);
  let driver = await new Builder().forBrowser('chrome').build();
  await driver.get("https://172.23.31.1//php/login.php");
  await driver.manage().window().setRect({ width: 1980, height: 1500 });
  await driver.findElement(By.id("user")).sendKeys("nocservice");
  await driver.findElement(By.id("passwd")).sendKeys("NOCpwd2020+");
  await driver.findElement(By.id("submit")).click();
  await driver.wait(until.elementLocated(By.id("monitor_img")), 30000);
  await driver.findElement(By.id("monitor")).click();
  await driver.findElement(By.css(".x-tree-selected > .x-tree-node-anchor > span")).click();
  await driver.findElement(By.id("ext-gen173")).click();
  await driver.findElement(By.xpath("//*[@id=\"ext-gen383\"]/div[2]")).click();
 } finally {
        // await driver.quit();
    }
});

